version: '3'
services:
  rabbit:
    build: clientRabbit
    environment:
      SERVER_HOSTNAME : "${SERVER_HOSTNAME}"
      PORT : "${PORT}"
      LEARNING_RATE: "${LEARNING_RATE}"
      EPOCHS: "${EPOCHS}"
    command: ["python", "client.py"]
    networks:
      intra_net:
        ipv4_address: 192.168.0.2
  capibara:
    build: clientCapibara
    environment:
      SERVER_HOSTNAME : "${SERVER_HOSTNAME}"
      PORT : "${PORT}"
      LEARNING_RATE: "${LEARNING_RATE}"
      EPOCHS: "${EPOCHS}"
    command: ["python", "client.py"]
    networks:
      intra_net:
        ipv4_address: 192.168.0.4
networks:
  intra_net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/16"
